# Generated by Django 4.2.4 on 2024-02-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Debates', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debate',
            name='category',
            field=models.CharField(choices=[('field1', 'Finance'), ('field2', 'Economics'), ('field3', 'Law'), ('field4', 'Medicine'), ('field5', 'Technology')], default=None, max_length=20),
            preserve_default=False,
        ),
    ]
