# Generated by Django 4.2.4 on 2024-02-16 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0001_initial'),
        ('Polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='author_profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='Members.profile'),
            preserve_default=False,
        ),
    ]
