# Generated by Django 4.2.4 on 2024-02-14 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Notes', to='Members.profile'),
        ),
        migrations.AddField(
            model_name='note',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Notes', to=settings.AUTH_USER_MODEL),
        ),
    ]
