# Generated by Django 4.2.4 on 2024-04-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0003_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='academic_field',
            field=models.CharField(choices=[('field1', 'Economics'), ('field2', 'Finance'), ('field3', 'Law'), ('field4', 'Medicine'), ('field5', 'Technology')], default='None Selected', max_length=20),
        ),
    ]
