# Generated by Django 4.2.4 on 2024-04-20 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0004_alter_profile_academic_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='profile',
            new_name='author_profile',
        ),
    ]
